### ISSUE TITLE
Is it appropriate to resize the ground truth image to 256x256 and calculate PSNR on it?

### ISSUE THREAD

**Issue by mayorx** [jammer345/SL-CycleGAN-Blind-Motion-Deblurring-in-Cycles-using-Sparse-Learning#1]
https://github.com/mayorx/PSNR_by_resize

**Comment by jammer345** [comment]
We did follow the DeblurGAN approach in their paper for resizing. Also I have personally replied to your mail. On 256x256 yeah our network achieves better PSNR and so does according your repo. I have taken down the metric values from the leaderboard since on 256x256 it might not be standard for comparison as of now. So, no worries!
